{application,system_boot,
             [{description,"An OTP application"},
              {vsn,"0.1.0"},
              {registered,[]},
              {mod,{system_boot_app,[]}},
              {applications,[kernel,stdlib]},
              {env,[]},
              {modules,[lib_system_boot,system_boot,system_boot_app,
                        system_boot_sup]},
              {licenses,["Apache-2.0"]},
              {links,[]}]}.
